version: '3'

services:
  db: 
    image: postgres
    container_name: profile_db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      PGDATA: ${PERSISTENCE}
    ports:
        - "5435:5432"

  django:
    build: ./api
    container_name: profile
    command: ash docker-entrypoint.sh
    volumes:
      - ./api:/api
    environment:
      HTTP_IP: ${HTTP_IP}
    ports:
      - "9042:9042"
    depends_on:
      - db
